version: "3"

services:
  game:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: bash -c "cd /app && go mod tidy && go run go/main.go"
    networks:
      - goaled_network

networks:
  goaled_network:
    external: true
